server:
  port: 8080
spring:
  application:
    name: txbb-eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    register-with-eureka: true
    fetch-registry: false