server:
  port: 9000
spring:
  application:
    name: txbb-user
  datasource:
    url: jdbc:mysql://localhost:3306/wechat1904
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka